pyth-network/per

auction-server/.sqlx/query-b8d0513ba6a00c8ad20b9c72677a69857e0f8ae8c2401c52f7f961c600574ffa.json
auction-server/migrations/20240624171707_bid_gas_limit.down.sql
auction-server/migrations/20240624171707_bid_gas_limit.up.sql
auction-server/src/auction.rs
auction-server/src/models.rs
auction-server/src/opportunity_adapter.rs
auction-server/src/state.rs
contracts/src/express-relay/Errors.sol
contracts/src/express-relay/ExpressRelay.sol
contracts/src/express-relay/Structs.sol
contracts/test/ExpressRelayIntegration.t.sol
contracts/test/ExpressRelayTestSetup.sol
contracts/test/ExpressRelayUnit.t.sol
contracts/test/OpportunityProvider.t.sol
contracts/test/helpers/MulticallHelpers.sol

This PR aims to add gas limit for each of the express relay multicall calls.

Add gas limit for internal calls in multicall

---

auction-server/Cargo.lock
auction-server/Cargo.toml
auction-server/src/auction.rs

This PR aims to relax threshold for minimum bid amount base on gas fees.

Update threshold for bid amount based on gas fees

---

auction-server/src/auction.rs
gas-oracle/src/lib.rs

This PR aims to relax minimum bid amount

Update minimum bid amount calculation

---

auction-server/.sqlx/query-1a07b19befac7096f62aa512f2c33f6282c0565025ba9ede3325705de09ea145.json
auction-server/.sqlx/query-33f3dda525887ab92aef0d37e718b87f933cb30d568abbc87b8112e7ab30c1bf.json
auction-server/Cargo.lock
auction-server/Cargo.toml
auction-server/migrations/20240627160811_bid_creation_time_index.down.sql
auction-server/migrations/20240627160811_bid_creation_time_index.up.sql
auction-server/src/auction.rs
auction-server/src/state.rs

This PR aims to update the bids state for those which lost the auction without being submitted to the chain.

Update the bids state which are not submitted to chain for an auction

---

auction-server/src/api.rs
auction-server/src/api/opportunity.rs
auction-server/src/api/profile.rs
auction-server/src/auction.rs
auction-server/src/models.rs
auction-server/src/opportunity_adapter.rs
auction-server/src/server.rs
auction-server/src/state.rs

This PR aims to add more logs for auction server

Add more logs

---

scripts/opportunity-provider/README.md
scripts/opportunity-provider/config.mainnet.json
scripts/opportunity-provider/index.ts
scripts/opportunity-provider/opportunities.json
scripts/opportunity-provider/opportunities.mainnet.json
scripts/opportunity-provider/opportunity.json
scripts/opportunity-provider/tokens.json

This PR aims to add load test option for opportunity provider

Add load test for provider

---

auction-server/Cargo.lock
auction-server/Cargo.toml
auction-server/src/api.rs
scripts/opportunity-provider/opportunities.mainnet.json

This PR aims to relabel unknown paths in the axum requests

Fix metrics endpoint for axum path

---

auction-server/Cargo.lock
auction-server/Cargo.toml
auction-server/src/auction.rs

This PR aims to add logging for low bid amount or high gas usage of submitted bids.

Add logs for bid limits on amount and gas

---

auction-server/Cargo.lock
auction-server/Cargo.toml
auction-server/src/api.rs
auction-server/src/api/bid.rs
auction-server/src/api/ws.rs
auction-server/src/auction.rs
auction-server/src/opportunity_adapter.rs

This PR aims to create auction server solana bid apis

Add solana api

---

auction-server/Cargo.lock
auction-server/Cargo.toml
auction-server/src/auction.rs
auction-server/src/serde.rs

This PR aims to update svm bid api

Update svm bid api

---

.github/workflows/push-rust-services.yaml
Dockerfile
per_sdk/Dockerfile

This PR aims to fix the build problem with anchor-cli installation

Fix ci anchor build

---

Tiltfile
contracts/svm/package.json
contracts/svm/test-validator-params.sh

Tested it with the js sdk and had some successful bids locally

feat: Add limo program in tilt

---

auction-server/Cargo.lock
contracts/svm/Cargo.lock
contracts/svm/programs/express_relay/Cargo.toml
contracts/svm/programs/express_relay/src/lib.rs
contracts/svm/programs/express_relay/src/utils.rs

Ran static analysis on SVM Express Relay program and incorporated some changes:
- added comments on validation of `config_router` in helper method
- added comment on rationale for `permission` as account instead of instruction data
- fixed underflow/overflow sources

SVM Static Analysis Improvements

---

auction-server/Cargo.lock
auction-server/Cargo.toml
auction-server/src/api.rs
auction-server/src/opportunity/api.rs
auction-server/src/opportunity/entities/opportunity_evm.rs

This PR aims to fix open api json schema generation

Fix open api schema

---

auction-server/src/traced_client.rs

This PR aims to add log for evm rpc errors

Add log for evm rpc errors

---

auction-server/Cargo.lock
auction-server/Cargo.toml
auction-server/src/config.rs
auction-server/src/main.rs
auction-server/src/server.rs
auction-server/src/traced_sender_svm.rs

This PR aims to add tracing for svm rpc client

Add tracing for svm rpc client

---

auction-server/Cargo.lock
auction-server/Cargo.toml
auction-server/src/api.rs
auction-server/src/api/bid.rs
auction-server/src/opportunity/api.rs
auction-server/src/state.rs

This PR aims to fix auction server docs issues. Additionally swagger docs is replaced with redoc as it has better ui.

Fix openapi docs for redoc and remove swagger

---

.github/workflows/push-rust-services.yaml
Tiltfile
auction-server/src/api.rs
auction-server/src/api/profile.rs
auction-server/src/state.rs
create_limo_profile.py
scripts/limonade/.gitignore
scripts/limonade/Dockerfile
scripts/limonade/README.md
scripts/limonade/package-lock.json
scripts/limonade/package.json
scripts/limonade/src/index.ts
scripts/limonade/tsconfig.json

feat: Limo opp updater

---

auction-server/Cargo.lock
auction-server/Cargo.toml
auction-server/src/auction.rs
auction-server/src/state.rs

Before the changes:
After the changes:

Fix: better api schemas

---

auction-server/src/auction.rs

This PR aims to fix issues for conclusion auctions with more than one bid for svm chain.

Fix error for wher we have submitted the same svm transaction twice

---

auction-server/src/auction.rs

This PR aims to fix the panic for getting empty bids list result

Fix get bids result for empty bids list

---

auction-server/src/auction.rs

This PR aims to fix auction conclusion with no bids

Fix concluding auctions with no bids

---

auction-server/src/api.rs
auction-server/src/api/profile.rs
auction-server/src/api/ws.rs
auction-server/src/auction.rs
auction-server/src/config.rs
auction-server/src/config/server.rs
auction-server/src/opportunity/api.rs
auction-server/src/opportunity/service/get_quote.rs
auction-server/src/opportunity/service/get_spoof_info.rs
auction-server/src/opportunity/token_spoof.rs
auction-server/src/state.rs
contracts/svm/cli/src/main.rs
contracts/svm/programs/dummy/src/lib.rs
contracts/svm/programs/express_relay/README.md
contracts/svm/programs/express_relay/src/lib.rs
contracts/svm/programs/express_relay/src/sdk/cpi.rs
contracts/svm/programs/express_relay/src/sdk/test_helpers.rs
contracts/svm/programs/express_relay/src/utils.rs
gas-oracle/src/lib.rs
vault-simulator/src/config.rs

This PR aims to fix doc strings which are not ended with period.

Fix doc strings to end with a period.

---

auction-server/src/api.rs
auction-server/src/opportunity/api.rs
auction-server/src/opportunity/entities/opportunity_svm.rs
auction-server/src/opportunity/repository/models.rs
auction-server/src/opportunity/service/get_quote.rs
sdk/js/src/examples/simpleSearcherLimo.ts
sdk/js/src/index.ts
sdk/js/src/serverTypes.d.ts
sdk/js/src/types.ts
sdk/python/express_relay/client.py
sdk/python/express_relay/models/svm.py
sdk/python/express_relay/searcher/examples/simple_searcher_svm.py

Removes blockhash from opportunities, updates the JS sdk to allow processing recent blockhashes sent by the auction server

feat: remove blockhash

---

auction-server/.sqlx/query-744013026c0b31750c2452f98851bb38e8bebeba59012b86ac6b0de653332cea.json
auction-server/src/state.rs

This PR aims to fix update query for svm lost bids

Fix svm lost bid query update

---

auction-server/src/opportunity/api.rs
sdk/js/package-lock.json
sdk/js/package.json
sdk/js/src/examples/simpleSearcherLimo.ts
sdk/js/src/index.ts
sdk/js/src/serverTypes.d.ts
sdk/js/src/types.ts
sdk/python/express_relay/client.py
sdk/python/express_relay/models/__init__.py
sdk/python/express_relay/models/base.py
sdk/python/express_relay/models/svm.py
sdk/python/express_relay/searcher/examples/simple_searcher_svm.py
sdk/python/pyproject.toml

This PR aims to add remove opportunties ws handler and js client method to er sdks

Add remove opportunties to sdk

---

auction-server/src/opportunity/service/mod.rs
auction-server/src/opportunity/service/remove_invalid_or_expired_opportunities.rs
auction-server/src/opportunity/workers.rs
auction-server/src/server.rs

This PR aims to add verification loop for svm chains

Add svm verification loop

---

sdk/js/src/examples/simpleSearcherLimo.ts

This PR aims to fix logging for remove opportunity in js sdk

Fix log for remove opportunity in js sdk

---

Tiltfile
scripts/limonade/package-lock.json
scripts/limonade/package.json
scripts/limonade/src/index.ts

This PR aims to add remove and resubmit opportunities to limonade

Add remove and resubmit opportunity

---

auction-server/.clippy.toml
auction-server/src/api.rs
auction-server/src/auction.rs
auction-server/src/opportunity/api.rs
auction-server/src/opportunity/entities/opportunity.rs
auction-server/src/opportunity/entities/opportunity_evm.rs
auction-server/src/opportunity/entities/opportunity_svm.rs
auction-server/src/opportunity/mod.rs
auction-server/src/opportunity/repository/get_in_memory_opportunity_by_id.rs
auction-server/src/opportunity/repository/remove_opportunity.rs
auction-server/src/opportunity/service/add_opportunity.rs
auction-server/src/opportunity/service/get_quote.rs
auction-server/src/opportunity/service/mod.rs
auction-server/src/opportunity/service/remove_invalid_or_expired_opportunities.rs
auction-server/src/opportunity/service/remove_opportunities.rs
auction-server/src/opportunity/workers.rs
sdk/js/package-lock.json
sdk/js/package.json
sdk/js/src/index.ts
sdk/js/src/serverTypes.d.ts
sdk/js/src/types.ts
sdk/python/express_relay/client.py
sdk/python/express_relay/models/__init__.py
sdk/python/express_relay/models/base.py
sdk/python/express_relay/models/evm.py
sdk/python/express_relay/models/svm.py
sdk/python/pyproject.toml

This PR aims to broadcast remove opportunity message for those opportunities that are expired.

Add remove opportunity broadcast for expired opportunities

---

sdk/python/express_relay/svm/limo_client.py

Replaces the TODO by some actual implementation

fix: wsol as output

---

Tiltfile
per_sdk/svm/setup_accounts.py
sdk/js/src/examples/simpleSearcherLimo.ts
sdk/python/express_relay/searcher/examples/simple_searcher_svm.py

This PR aims to add latency and bid margin for simple searchers. It separates the private key for js and python searchers to test concurrency better while using tilt

Add latency and margin to bid for simple searchers

---

auction-server/src/server.rs

Running the migration command printed no helpful logs to make sure it's working correctly

fix: better logging on migration command

---

scripts/limonade/package-lock.json
scripts/limonade/package.json

bump: limonade

---

auction-server/src/auction.rs

nitpick: use serialized_size

---

scripts/dex-router/src/const.ts
scripts/dex-router/src/index.ts
scripts/dex-router/src/utils/computeBudget.ts
scripts/dex-router/src/utils/health.ts
scripts/limonade/src/index.ts

This PR introduces improved alerting around RPC and Express Relay endpoint health for scripts
This includes
- a check of the block time of the most recent finalized block. This is a fairly conservative check, but it is aimed at decreasing false positive alert rates. We will improve this check in the future.
- a check of the liveness of the express relay server

fix: improved alerting for scripts

---

auction-server/src/auction.rs

- Better error message when we know which signature is not valid
- Check that relayer pubkey is actually in the tx as a signer
- Better error if no opportunity was found

feat: better signature checking

---

auction-server/Cargo.lock
auction-server/Cargo.toml
auction-server/src/auction.rs
auction-server/src/state.rs
auction-server/src/watcher.rs
sdk/js/package-lock.json
sdk/js/package.json
sdk/js/src/examples/simpleSearcherLimo.ts
sdk/js/src/serverTypes.d.ts
sdk/python/express_relay/models/svm.py
sdk/python/express_relay/searcher/examples/simple_searcher_svm.py
sdk/python/pyproject.toml

- Send the latest priority fees to the websocket subscribers
- Reject bids that have low priority fees
- Use priority fees in the sdks

feat: Enforce prioritization fees

---

scripts/dex-router/src/utils/computeBudget.ts
sdk/python/express_relay/svm/generated/limo/accounts/global_config.py
sdk/python/express_relay/svm/generated/limo/accounts/order.py
sdk/python/express_relay/svm/generated/limo/errors/custom.py
sdk/python/express_relay/svm/generated/limo/instructions/__init__.py
sdk/python/express_relay/svm/generated/limo/instructions/close_order_and_claim_tip.py
sdk/python/express_relay/svm/generated/limo/instructions/create_order.py
sdk/python/express_relay/svm/generated/limo/instructions/flash_take_order_end.py
sdk/python/express_relay/svm/generated/limo/instructions/flash_take_order_start.py
sdk/python/express_relay/svm/generated/limo/instructions/take_order.py
sdk/python/express_relay/svm/generated/limo/instructions/update_global_config_admin.py
sdk/python/express_relay/svm/generated/limo/types/update_global_config_mode.py
sdk/python/express_relay/svm/generated/limo/types/update_global_config_value.py
sdk/python/express_relay/svm/limo_client.py
sdk/python/pyproject.toml

This PR updates the Python SDK to the most recent version of Limo.

fix: update python sdk to limo 0.7.0

---

scripts/limonade/package-lock.json
scripts/limonade/package.json

This PR aims to upgrade the express relay version for limonade script

Upgrade the express relay js sdk for limonade

---

auction-server/Cargo.lock
auction-server/Cargo.toml

This PR aims to update auction server version to 0.13.0

Update auction server version

---

auction-server/src/auction/service/auction_manager.rs

This PR aims to trigger the svm submission auction loop every 400ms instead of listening to new slot

Add trigger for handling svm auction every 400 ms

---

scripts/dex-router/src/index.ts
scripts/swap-beacon/src/index.ts
sdk/js/package-lock.json
sdk/js/package.json
sdk/js/src/index.ts

- bubble up status codes so we can filter on 5xx in the logs
- add ping/pong to the websocket to ensure we notice it the connection gets interrupted

feat: better error logs

---

auction-server/README.md
auction-server/src/api.rs
auction-server/src/auction/entities/bid.rs
auction-server/src/auction/repository/add_auction.rs
auction-server/src/auction/repository/conclude_auction.rs
auction-server/src/auction/repository/remove_in_memory_submitted_auction.rs
auction-server/src/auction/repository/submit_auction.rs
auction-server/src/auction/service/auction_manager.rs
auction-server/src/auction/service/conclude_auction.rs
auction-server/src/auction/service/handle_auction.rs
auction-server/src/auction/service/handle_bid.rs
auction-server/src/auction/service/update_bid_status.rs

This PR aims to add more fields for tracing

Add more fields to tracing

---

auction-server/src/main.rs

This PR aims to filter only traces for `auction_server`

Add filter for tracing

---

.github/workflows/publish-js-sdks.yml
.github/workflows/publish-solidity-sdk.yml

This PR aims to fix the sdk publish in ci workflow

Fix publish package

---

scripts/dex-router/src/index.ts

feat: do not try to submit bid if jup output amount is lower than what we need

---

auction-server/src/main.rs
auction-server/src/opportunity/service/get_spoof_info.rs
auction-server/src/opportunity/service/handle_opportunity_bid.rs

This PR aims to remove external logs from auction server

Remove external logs

---

sdk/js/src/examples/simpleSearcherLimo.ts
sdk/python/express_relay/searcher/examples/simple_searcher_svm.py

Update python simple searcher docstring and function signature to be consistent with JS

fix: docstrings

---

.github/workflows/push-services.yaml
.pre-commit-config.yaml
Dockerfile

This PR aims to fix the ci pre-commit for repo and build process for auction server

Fix precommit

---

Cargo.lock
sdk/rust/Cargo.toml
sdk/rust/src/evm.rs
sdk/rust/src/lib.rs

This PR aims to add some doc string for rust sdk client implementation

Add docs for rust sdk

---

contracts/evm/README.md
contracts/evm/test/ExpressRelayIntegration.t.sol

- **README.md**: Corrected "commited" to "committed" for clarity.
- **ExpressRelayIntegration.t.sol**: Corrected "permisison" to "permission" for accuracy.
Improved the readability and professionalism of documentation and code comments.

 Fix typos in README.md and ExpressRelayIntegration.t.sol

---

vault-simulator/src/simulator.rs

**Fix Typo in `simulator.rs`**
This pull request fixes a typo in the `simulator.rs` file, specifically correcting "colateral" to the proper spelling "collateral" in an error message.
- **File Modified:** `vault-simulator/src/simulator.rs`
- **Summary of Changes:**
- Corrected the spelling of "colateral" to "collateral" in the error handling logic when sampling tokens for collateral and debt.
This correction ensures proper spelling in the error message, improving readability and reducing confusion for developers.
---
**Allow edits by maintainers:** [x]

**Fix Typo in `simulator.rs`**

---

contracts/svm/programs/express_relay/src/error.rs
contracts/svm/programs/express_relay/src/lib.rs
contracts/svm/programs/express_relay/src/state.rs
contracts/svm/programs/express_relay/src/swap.rs
contracts/svm/programs/express_relay/src/token.rs
contracts/svm/programs/express_relay/src/utils.rs

This requires https://github.com/pyth-network/per/pull/305 to be merged

feat: swap program v2

---

contracts/svm/testing/src/helpers.rs
contracts/svm/testing/tests/initialize.rs
contracts/svm/testing/tests/set_admin.rs
contracts/svm/testing/tests/set_protocol_split.rs
contracts/svm/testing/tests/set_relayer.rs
contracts/svm/testing/tests/set_splits.rs
contracts/svm/testing/tests/set_swap_platform_fee.rs
contracts/svm/testing/tests/submit_bid.rs
contracts/svm/testing/tests/swap.rs
contracts/svm/testing/tests/withdraw_fees.rs

Added one last test. Had to refactor `assert_custom_error` because it's a new type of error.

test: add fees overflow test

---

.pre-commit-config.yaml
examples/easy_lend/src/monitor.ts
scripts/dex-router/src/index.ts
scripts/dex-router/src/router/jupiter.ts
scripts/dex-router/src/types.ts
scripts/limonade/src/index.ts
scripts/limonade/src/price-config.ts
scripts/opportunity-provider-limo/index.ts
scripts/opportunity-provider/index.ts
scripts/swap-beacon/src/adapter/odos.ts
scripts/swap-beacon/src/index.ts
scripts/swap-beacon/src/types.ts
sdk/js/README.md
sdk/js/src/const.ts
sdk/js/src/evm.ts
sdk/js/src/examples/dummyTypes.d.ts
sdk/js/src/examples/simpleSearcherEvm.ts
sdk/js/src/examples/simpleSearcherSvm.ts
sdk/js/src/examples/testingSearcherPing.ts
sdk/js/src/examples/testingSearcherSvm.ts
sdk/js/src/expressRelayTypes.d.ts
sdk/js/src/index.ts
sdk/js/src/svm.ts

Let's bump the prettier pre-commit hook to match the pre-commit that we have in package.json
This is required for CI to work on https://github.com/pyth-network/per/pull/331

bump: prettier

---

scripts/limonade/package.json
scripts/limonade/src/index.ts

The dependency update for the swap staging app broke limonade.

chore: fix limonade

---

Tiltfile
sdk/rust/testing-searcher/src/main.rs

This PR aims to fix sdk problem with local tilt

Fix sdks for swap

---

Dockerfile

should correctly implement pinning as with https://github.com/pyth-network/per/pull/353

fix: pin foundryup release

---

auction-server/api-types/src/bid.rs
auction-server/api-types/src/ws.rs
auction-server/src/api.rs
auction-server/src/api/ws.rs
auction-server/src/auction/api.rs
auction-server/src/auction/entities/bid.rs
auction-server/src/auction/repository/get_in_memory_auction_bid_by_id.rs
auction-server/src/auction/repository/get_in_memory_auction_by_bid_id.rs
auction-server/src/auction/repository/get_or_create_in_memory_bid_lock.rs
auction-server/src/auction/repository/mod.rs
auction-server/src/auction/repository/remove_in_memory_bid_lock.rs
auction-server/src/auction/service/auction_manager.rs
auction-server/src/auction/service/cancel_bid.rs
auction-server/src/auction/service/mod.rs
auction-server/src/auction/service/submit_quote.rs

This PR aims to add cancel bid api for svm bids

Add cancel bid api

---

Cargo.lock
auction-server/Cargo.toml
auction-server/api-types/src/opportunity.rs
auction-server/src/opportunity/entities/quote.rs
tilt-scripts/svm/test_swap.py

This PR aims to add `submit_quote` call to the test swap script in the `tilt_scripts`.

Add submit quote to tilt swap script

---

Cargo.lock
auction-server/api-types/Cargo.toml
sdk/js/package.json
sdk/python/pyproject.toml
sdk/rust/Cargo.toml

This PR aims to update the js, python, and rust sdk versions

Upgrade sdk versions

---

auction-server/Cargo.toml
auction-server/src/auction/service/verification.rs

This PR aims to add more instruction check in auction server for bids on swap opportunities

Add instruction check to swap bids in auction server

---

pnpm-lock.yaml
pnpm-workspace.yaml
scripts/limonade/package.json
scripts/rfq-stress-test/.gitignore
scripts/rfq-stress-test/config.json
scripts/rfq-stress-test/index.ts
scripts/rfq-stress-test/package.json
scripts/rfq-stress-test/tsconfig.json
sdk/js/package.json

This PR aims to add rfq stress test script to per monorepo

Add rfq stress test

---

auction-server/src/opportunity/service/get_quote.rs

This is useful for our current testing to make sure searchers handle both FeeToken variants

feat: Better fee token determination

---

auction-server/src/auction/repository/add_auction.rs
auction-server/src/auction/repository/get_in_memory_auction_by_id.rs
auction-server/src/auction/repository/get_in_memory_auctions.rs
auction-server/src/auction/repository/mod.rs
auction-server/src/auction/repository/remove_in_memory_auction.rs
auction-server/src/auction/repository/update_bid_status.rs
auction-server/src/auction/repository/update_in_memory_auction.rs

This PR aims to replace in memory auction vector with hash map

Replace in memory auction vector with HashMap

---

auction-server/src/opportunity/repository/add_opportunity.rs
auction-server/src/opportunity/repository/db.rs
auction-server/src/opportunity/repository/get_in_memory_opportunities.rs
auction-server/src/opportunity/repository/get_in_memory_opportunities_by_key.rs
auction-server/src/opportunity/repository/get_opportunities.rs
auction-server/src/opportunity/repository/mod.rs
auction-server/src/opportunity/repository/refresh_in_memory_opportunity.rs
auction-server/src/opportunity/repository/remove_opportunities.rs
auction-server/src/opportunity/repository/remove_opportunity.rs
auction-server/src/opportunity/service/add_opportunity.rs
auction-server/src/opportunity/service/get_config.rs
auction-server/src/opportunity/service/mod.rs
auction-server/src/opportunity/service/verification.rs

Make the notations cleaner for opportunity repo

chore: make opportunity db a trait object

---

sdk/js/src/idl/idlExpressRelay.json
sdk/python/express_relay/idl/idlExpressRelay.json

after https://github.com/pyth-network/per/pull/406

chore: update idls

---

Cargo.lock
auction-server/Cargo.toml
auction-server/src/api.rs
auction-server/src/auction/service/mod.rs
auction-server/src/auction/service/verification.rs
auction-server/src/kernel/entities.rs
auction-server/src/opportunity/service/add_opportunity.rs
auction-server/src/opportunity/service/get_live_opportunities.rs
auction-server/src/server.rs

This PR aims to add more test for `verify_bid` function for swap opps

Add simple swap instruction test

---

Tiltfile
auction-server/config.sample.yaml
auction-server/src/config.rs
auction-server/src/opportunity/service/get_quote.rs
auction-server/src/opportunity/service/mod.rs
integration.py

This PR adds a way to specify the hierarchy of fee tokens.

Feat: better determination for fee tokens

---

auction-server/src/api/ws.rs

This PR aims to increase number of max active requests for ws subscribers

Update max active concurrent requests for ws subscribers

---

auction-server/src/api.rs
auction-server/src/api/ws.rs
auction-server/src/config/server.rs
auction-server/src/opportunity/service/mod.rs
auction-server/src/server.rs

This PR aims to add rate limiter to total number of active subscribers per ip

Add rate limiter for total number of subscriber per ip

---

auction-server/src/auction/service/verification.rs

feat: add indexes to verification errors

---

auction-server/src/server.rs

This PR aims to update default metrics buckets for the auction server monitoring

Update default metrics buckets

---

.github/workflows/ci-pre-commit.yml
.github/workflows/publish-express-relay-api-types.yml
.pre-commit-config.yaml
Dockerfile
auction-server/src/auction/service/verification.rs
contracts/svm/programs/dummy/src/lib.rs
contracts/svm/programs/express_relay/src/lib.rs
rust-toolchain.toml

to fix https://github.com/pyth-network/per/actions/runs/14042413023/job/39315473223

bump: rust version

---

auction-server/src/auction/service/verification.rs
auction-server/src/opportunity/entities/opportunity_svm.rs
auction-server/src/opportunity/repository/models.rs
auction-server/src/opportunity/service/get_quote.rs

For consistency with the api type.

chore: rename token_account_initialization_config

---

contracts/svm/programs/express_relay/src/lib.rs
contracts/svm/programs/express_relay/src/swap.rs
contracts/svm/testing/src/express_relay/swap.rs
contracts/svm/testing/src/lib.rs
contracts/svm/testing/src/setup.rs
contracts/svm/testing/src/token.rs
contracts/svm/testing/tests/submit_bid.rs
contracts/svm/testing/tests/swap.rs

I made some structural changes to allow easier overrides.
Previously, if we wanted to add an additional override field, we had to change each and every test to specify we don't want to override that field there which was inefficient.

Program 2.0 tests

---

auction-server/src/auction/service/submit_quote.rs

This PR aims to update the error messages in the submit quote

Update submit quote error messages

---

auction-server/src/auction/repository/add_bid.rs
auction-server/src/auction/service/cancel_bid.rs
auction-server/src/auction/service/get_bid.rs
auction-server/src/auction/service/get_bids.rs
auction-server/src/auction/service/handle_auction.rs
auction-server/src/auction/service/handle_bid.rs
auction-server/src/auction/service/submit_quote.rs
auction-server/src/auction/service/update_bid_status.rs
auction-server/src/auction/service/update_recent_prioritization_fee.rs
auction-server/src/auction/service/verification.rs
auction-server/src/main.rs
auction-server/src/opportunity/service/get_quote.rs
auction-server/src/opportunity/service/get_quote_request_account_balances.rs

This PR aims to fix the issue with logging the errors of the traces

Fix tracing error level in instrument

---

tilt-scripts/svm/test_swap.py

it defaults to finalized so we are simulating against stale state

fix: use processed preflight commitment

---

auction-server/src/api.rs
auction-server/src/auction/service/mod.rs
auction-server/src/opportunity/service/get_quote.rs
auction-server/src/opportunity/service/mod.rs
auction-server/src/opportunity/service/unwrap_referral_fee_info.rs
auction-server/src/per_metrics.rs
auction-server/src/server.rs
auction-server/src/state.rs

In this mr I added the first few tests to get quote, and tried making it more test ready in general, ill create a followup that wraps the rpc calls so we can test those as well. Also further tests for creating the quote request

chore: Add more tests to get quote

---

CHANGELOG.md
auction-server/api-types/src/bid.rs
sdk/js/src/serverTypes.d.ts
sdk/python/express_relay/models/base.py
sdk/python/express_relay/models/svm.py

This PR aims to add bid submission failed status to sdks

Add bid submission failed status to sdk

---

Cargo.lock
auction-server/Cargo.toml

This PR aims to update the auction server version to 0.23.0

Update auction server version to 0.23.0

---

Cargo.lock
auction-server/api-types/Cargo.toml
sdk/js/package.json
sdk/python/pyproject.toml
sdk/rust/Cargo.toml

This PR aims to update sdk versions

Update sdk vesions

---

auction-server/src/auction/service/workers.rs
auction-server/src/server.rs

This PR aims to remove evm workers

Remove evm workers

---

auction-server/src/auction/api.rs
auction-server/src/auction/service/mod.rs
auction-server/src/opportunity/service/mod.rs
auction-server/src/opportunity/workers.rs
auction-server/src/server.rs
auction-server/src/state.rs

This PR aims to remove opportuntiy evm service setup

Remove opportunity evm setup from server

---

auction-server/src/opportunity/service/get_quote_request_account_balances.rs

token accounts that have some sol but no data should be marked as unitialized

fix: initialized bug

---

auction-server/src/kernel/rpc_client_svm_tester.rs
auction-server/src/opportunity/service/get_quote.rs
auction-server/src/opportunity/service/get_quote_request_account_balances.rs

adds tests using the new svm rpc test helper to check non indicative quote creation as well

chore: Add connected user balance tests

---

auction-server/src/auction/service/submit_quote.rs

This PR aims to fix issue with removing in memory bid lock

Fix in memory bid lock removal

---

auction-server/src/api.rs
auction-server/src/auction/service/submit_quote.rs

This PR aims to update error codes of the submit quote service / api

Update submit quote error codes

---

CHANGELOG.md
Cargo.lock
auction-server/Cargo.toml
auction-server/api-types/Cargo.toml
sdk/js/package.json
sdk/python/pyproject.toml
sdk/rust/Cargo.toml

This PR aims to update versions for SDKs and auction server

Update versions and changelog

---

auction-server/src/config/server.rs
auction-server/src/server.rs

This PR aims to add min db pool connection config

Add minimum number of DB pool connections

---

pnpm-lock.yaml
pnpm-workspace.yaml
scripts/rfq-dynamic-deadline/.gitignore
scripts/rfq-dynamic-deadline/index.ts
scripts/rfq-dynamic-deadline/package.json
scripts/rfq-dynamic-deadline/tsconfig.json

This PR aims to add a script for testing rfq different deadlines

Add rfq dynamic deadline comparison

---

Cargo.lock
auction-server/Cargo.toml

This PR aims to update server versions

Update auction server version to 0.27.0

---

Cargo.lock
auction-server/Cargo.toml
auction-server/clickhouse_migrations/0003_add_bid_swap.sql
auction-server/clickhouse_migrations/0004_add_bid_limo.sql
auction-server/src/auction/entities/bid.rs
auction-server/src/auction/repository/add_bid_analytics.rs
auction-server/src/auction/repository/mod.rs
auction-server/src/auction/repository/models.rs
auction-server/src/auction/service/get_bid_transaction_data.rs
auction-server/src/auction/service/mod.rs
auction-server/src/auction/service/submit_quote.rs
auction-server/src/auction/service/update_bid_status.rs
auction-server/src/auction/service/verification.rs
auction-server/src/kernel/analytics_db.rs
auction-server/src/opportunity/repository/models.rs
auction-server/src/opportunity/service/get_quote.rs
auction-server/src/server.rs

This PR aims to add bids to clickhouse db for analytics purposes. It adds a new bid every time a status update was successful on a bid.

Add bid to clickhouse for analytics

---

Cargo.lock
auction-server/Cargo.toml
auction-server/src/opportunity/service/get_quote.rs

This PR fixes a bug whereby opportunities with 0 amount specified could be created, added to the db, and broadcast to subscribers.

Fix: zero amount opportunity bug

---

Cargo.lock
auction-server/Cargo.toml
auction-server/src/auction/repository/remove_in_memory_bid_lock.rs
auction-server/src/auction/repository/remove_in_memory_pending_bids.rs
auction-server/src/auction/repository/update_bid_status.rs
auction-server/src/auction/service/auction_manager.rs
auction-server/src/auction/service/get_bid_transaction_data.rs
auction-server/src/auction/service/submit_quote.rs

This PR adds more tracing to the flow of `submit_quote`. This will allow for more precise measurement and understanding of where latency is coming from in the `submit_quote` flow.

feat: add more tracing to `submit_quote`
