pyth-network/per

.github/workflows/push-rust-services.yaml, scripts/swap-beacon/.dockerignore, scripts/swap-beacon/Dockerfile, scripts/swap-beacon/README.Docker.md, scripts/swap-beacon/compose.yaml, scripts/swap-beacon/package-lock.json, scripts/swap-beacon/package.json
This PR aims to create docker image for swap beacon
=> Add deployment for swap beacon

scripts/swap-beacon/package-lock.json, scripts/swap-beacon/package.json, scripts/swap-beacon/src/index.ts
We rely on the heartbeat the server sends to the client to make sure the connection is still alive.
By calling the terminate function on the websocket, the whole process will exit. 
Solution based on:
https://github.com/websockets/ws?tab=readme-ov-file#how-to-detect-and-close-broken-connections
=> Exit on no ping

.github/workflows/ci-pre-commit.yml, .github/workflows/push-rust-services.yaml, Dockerfile, auction-server/Cargo.toml, auction-server/build.rs, auction-server/src/auction.rs, auction-server/src/server.rs, auction-server/src/state.rs
This PR aims to extract bid data from svm transaction
=> Add svm bid data extraction from transaction

auction-server/src/auction.rs
This PR aims to use slot trigger instead of block trigger for submission and conclusion loops on svm chains
=> Update svm trigger to slot instead of block

auction-server/src/auction.rs
This PR aims to fix auction loop submission for svm chains
=> Fix svm auction loop

auction-server/src/opportunity/api.rs, auction-server/src/opportunity/entities/opportunity_svm.rs, auction-server/src/opportunity/repository/models.rs
SDK requires the order address for filling them
=> feat: Add limo order address

.pre-commit-config.yaml, auction-server/src/models.rs, auction-server/src/opportunity/api.rs, auction-server/src/opportunity/entities/opportunity.rs, auction-server/src/opportunity/repository/models.rs, auction-server/src/opportunity/service/estimate_price.rs, auction-server/src/opportunity/service/mod.rs, auction-server/src/state.rs, contracts/svm/testing/src/express_relay/submit_bid.rs, contracts/svm/testing/src/helpers.rs, vault-simulator/src/simulator.rs
there is an on-going issue where if you run clippy with the `--fix` flag, the return code is always 0 even when it should fail.
I just removed the fix param for now to make sure we catch such issues firsthand.
=> fix: clippy warns fail pre-commit now

scripts/limonade/package-lock.json, scripts/limonade/package.json, scripts/limonade/src/index.ts
This PR aims to ignore closed accounts in limonade scripts and remove the removal loop. The auction server will expire opps after a minute, so we don't need to send an update for closed accounts and server will take care of it.
=> Remove removal loop from limonade

sdk/python/express_relay/svm/generated/limo/accounts/global_config.py, sdk/python/express_relay/svm/generated/limo/accounts/order.py, sdk/python/express_relay/svm/generated/limo/errors/custom.py, sdk/python/express_relay/svm/generated/limo/instructions/__init__.py, sdk/python/express_relay/svm/generated/limo/instructions/flash_take_order_end.py, sdk/python/express_relay/svm/generated/limo/instructions/flash_take_order_start.py, sdk/python/express_relay/svm/generated/limo/instructions/take_order.py, sdk/python/express_relay/svm/generated/limo/types/update_global_config_mode.py, sdk/python/express_relay/svm/limo_client.py
Apply the changes from `@kamino-finance/limo-sdk` 0.6.0 to the Python sdk.
TODO:
- Apply rounding errors fix
- Fix WSOL as output
=> fix: backport js changes to python 

auction-server/Cargo.lock, auction-server/Cargo.toml, auction-server/src/state.rs
This PR aims to resolve the bug of get_bid_status api for svm bids with expired status
=> Fix get bid status for svm expired

sdk/python/express_relay/svm/limo_client.py
Turns out bytes(1) was initialized to a 0 so we weren't calling the idempotent version
=> fix: idempotent ata

auction-server/src/auction.rs, auction-server/src/server.rs, auction-server/src/state.rs
Use tokio broadcast to have multiple subscribers to rpc logs. One for concluding the auctions and the other for stopping resubmission of transactions.
=> feat: retry logic for svm sending transactions

scripts/dex-router/README.md, scripts/dex-router/package-lock.json, scripts/dex-router/package.json, scripts/dex-router/src/index.ts
This PR adds an Express Relay server API key flag to the dex router to help identify the source of bids on the database side. It also adds some documentation to the README
=> fix: add api key + docs on flags

.eslintrc.js, scripts/limonade/package-lock.json, scripts/limonade/package.json, scripts/limonade/src/index.ts
- remove direct `/live` checks
- send all `submitOpportunity` calls concurrently
- filter out duplicate opportunity errors to not pollute stderr
- handle rejects in the callback inside `onProgramAccountChange`
=> limonade: bump express-relay sdk and remove direct http checks

README.md
**Description:**  
Corrected a capitalization error in the "Development with Tilt" section of the documentation.  
- The phrase *"Here is what tilt up does in order:"* has been updated to *"Here is what Tilt up does in order:"*.  
- The word "Tilt" is now properly capitalized to align with the tool's official name.  
This fix enhances the professionalism and clarity of the documentation, ensuring that readers can easily recognize "Tilt" as a proper noun and the name of a specific development tool. Accurate and polished documentation is crucial for maintaining user trust and reducing potential confusion.
=> Fix capitalization error in "Development with Tilt" section

scripts/limonade/src/index.ts
We might want to make limonade crash if the websocket is not working (since that's the lowest latency path for opportunities to be published).
This PR adds a timeout for the websocket leveraging the onSlotChange subscription. If there are not new slots for 30 seconds, we will assume the websocket doesn't work and crash.
=> chore: add websocket timeout to limonade

auction-server/src/auction/service/handle_bid.rs, auction-server/src/auction/service/simulator.rs, auction-server/src/auction/service/verification.rs, sdk/python/express_relay/svm/limo_client.py
This is in progress on litesvm package:
https://github.com/LiteSVM/litesvm/issues/98
For testing, I added a dummy instruction into searchers transaction that transfers 3 lamports to an empty account. It was not failing before the change but it was after the change.
=> fix: check rent exemptions manually after the simulation

auction-server/src/auction/api.rs
I updated the text a bit while working on the docs 
https://github.com/pyth-network/documentation/pull/528
=> feat: update bid status text to match docs

pnpm-lock.yaml, scripts/limonade/README.md, scripts/limonade/package.json, scripts/limonade/price-config.sample.yaml, scripts/limonade/price-config.yaml, scripts/limonade/src/index.ts, scripts/limonade/src/price-config.ts
This pull request adds some logic to limonade to ignore orders that are out-of-money. With a 5% threshold, if currently reduces the amount of orders to submit from 200 to 50. 
Features:
- If no `price-config` is provided it will just revert to the old behavior of submitting everything
- If `price-config` is provided it will crash if the hermes streaming is interrupted or times out. This is so kubernetes restarts limonade.
- If no price is available for `quote` or `base` (because one of the two is not listed in `price-config.yaml`  or because the price from Hermes is stale), it will revert to the old behavior of submitting all opportunities
=> feat: make limonade smart

auction-server/src/auction/service/auction_manager.rs, auction-server/src/auction/service/conclude_auction.rs, auction-server/src/auction/service/workers.rs
This PR aims to fix the svm slow conslusion issue
Sometimes the websocket hears about confirmation before the RPC client. In the previous version the conclude auction was dependent on RPC client also seeing the confirmation transaction. Now in the conclusion log listener worker, the code only use the log to conclude the auction.
=> Fix svm slow conclusion

auction-server/api-types/src/bid.rs, sdk/rust/src/lib.rs
This bug was crashing tilt I think
=> fix: chain_id routes

scripts/limonade/src/index.ts, sdk/js/src/index.ts
I yolo merged some unwanted changes
=> fix: revert unwanted changes

sdk/js/package.json, sdk/js/src/index.ts
This PR aims at fixing the sdk swallowing some auction server error messages like the 422 we saw on Tuesday last week:
before: 
`ClientError: Auction server http error 422 - undefined`
after:
`ClientError: Auction server http error 422 - "Failed to deserialize the JSON body into the target type: data did not match any variant of untagged enum OpportunityCreate"`
=> fix: sdk to not swallow errors

scripts/swap-beacon/package.json, scripts/swap-beacon/src/adapter/odos.ts
For illiquid tokens there can be over %5 slippage on AMMs and the previous max was just 8 * 0.005 = %4. Also the doubling method, skipped from %4 to %8 which can cause the sell tokens to become larger than buy tokens easily, So changed it to linear scaling.
=> feat: increase slippage threshold slower and until a higher max

sdk/js/package.json, sdk/js/src/examples/simpleSearcherLimo.ts, tilt-scripts/poetry.lock, tilt-scripts/pyproject.toml
This PR:
1. fixes a tilt-scripts solana version issue--we were using `^0.34.3` for the solana-py package, but later versions of solana-py deprecate the Transaction module in favor of solders. We rely on this Transaction module within solana-py, so for now I set the solana-py version to strictly `0.34.3`.
2. fixes an eslint issue in the js sdk around ES6 module require/import incompatibility
TODO
=> Fix tilt/ci issues

auction-server/api-types/src/opportunity.rs, pnpm-lock.yaml, sdk/js/package.json, sdk/js/src/index.ts, sdk/js/src/serverTypes.d.ts, sdk/js/src/types.ts
This PR adds a method to submit a quote request from the client. It only adds this to the TS sdk, and it is not complete--it is meant just to serve as a quick reference for integrating routers.
=> feat: create quote response submit method, typescript

.pre-commit-config.yaml, sdk/python/express_relay/client.py
This pre-commit is slow and awkward, we only need to run when something actually changes
=> fix: run workspace precommit only when rust files are touched

scripts/limonade/package.json, scripts/limonade/src/price-config.ts
cyan limonade is crashing because it can't get the decimals of a token22 mint
=> fix: support token 2022

auction-server/migrations/20250110093007_permission_key_svm_discriminator.down.sql, auction-server/migrations/20250110093007_permission_key_svm_discriminator.up.sql
This PR fixes the mismatch btwn the database permission key format and the server permission key format for chain_type `svm`, which was introduced by changes in #315
=> fix migration permission key svm

tilt-scripts/Dockerfile
since https://github.com/pyth-network/per/pull/314, tilt-scripts depends on the svm python sdk, so we need to include it in the docker build
=> fix: add sdk paths to tilt-scripts dockerfile

contracts/svm/testing/src/express_relay/swap.rs, contracts/svm/testing/tests/swap.rs
=> test: more program tests

auction-server/api-types/src/opportunity.rs, auction-server/config.sample.yaml, auction-server/src/config.rs, auction-server/src/opportunity/entities/opportunity_svm.rs, auction-server/src/opportunity/repository/get_token_program.rs, auction-server/src/opportunity/repository/mod.rs, auction-server/src/opportunity/repository/models.rs, auction-server/src/opportunity/service/get_quote.rs, auction-server/src/opportunity/service/get_token_program.rs, auction-server/src/opportunity/service/mod.rs, auction-server/src/state.rs, integration.py
This PR adds the pulling and caching of token programs for mints to the server side. The token programs are passed in the QuoteSvm object to the caller.
=> add token programs to server

tilt-scripts/svm/initialize_programs.py
Before this PR, the instructions builders would use the production program id no matter the `--express-relay-program` arg
=> feat: make initialize script compatible with other program ids

Cargo.lock, Cargo.toml, Tiltfile, auction-server/Cargo.toml, auction-server/api-types/Cargo.toml, auction-server/src/auction/service/verification.rs, auction-server/src/opportunity/entities/opportunity_svm.rs, contracts/svm/Cargo.lock, contracts/svm/programs/dummy/tests/test_e2e.rs, contracts/svm/programs/express_relay/Cargo.toml, contracts/svm/programs/express_relay/src/sdk/helpers.rs, contracts/svm/programs/express_relay/src/sdk/mod.rs, contracts/svm/programs/express_relay/src/sdk/test_helpers.rs, sdk/js/src/expressRelayTypes.d.ts, sdk/js/src/idl/idlExpressRelay.json, sdk/rust/Cargo.toml, sdk/rust/simple-searcher/Cargo.toml, sdk/rust/simple-searcher/src/lib.rs, sdk/rust/simple-searcher/src/main.rs, sdk/rust/src/evm.rs, sdk/rust/src/lib.rs, sdk/rust/src/svm.rs, sdk/rust/testing-searcher/Cargo.toml, sdk/rust/testing-searcher/src/main.rs, tilt-scripts/svm/setup_accounts.py
This PR aims to add svm functionalities for rust sdk
=> Add submit bid instruction

auction-server/api-types/src/bid.rs, auction-server/api-types/src/lib.rs, auction-server/api-types/src/quote.rs, auction-server/src/api.rs, auction-server/src/auction/api.rs, auction-server/src/auction/repository/get_in_memory_bid_by_id.rs, auction-server/src/auction/repository/mod.rs, auction-server/src/auction/service/auction_manager.rs, auction-server/src/auction/service/mod.rs, auction-server/src/auction/service/submit_quote.rs, auction-server/src/auction/service/verification.rs, auction-server/src/opportunity/entities/quote.rs, auction-server/src/opportunity/service/get_quote.rs
This PR aims to add submit quote endpoint to auction server
=> Add submit quote api

auction-server/api-types/src/bid.rs
This PR aims to temporary fix rust sdk issue on bid status enum variant.
When the sdk receive a Lost status with No data inside, it'll assume that the variant is for EVM (Which maybe wrong). Later we need to add a tag to it for serailization.
=> Update bid status variant order

Cargo.lock, auction-server/Cargo.toml, auction-server/api-types/src/bid.rs, auction-server/api-types/src/lib.rs, auction-server/api-types/src/opportunity.rs, auction-server/src/api/ws.rs, auction-server/src/kernel/traced_sender_svm.rs, auction-server/src/opportunity/repository/add_opportunity.rs, auction-server/src/opportunity/repository/db.rs, auction-server/src/opportunity/repository/get_in_memory_opportunities.rs, auction-server/src/opportunity/repository/get_in_memory_opportunities_by_key.rs, auction-server/src/opportunity/repository/get_opportunities.rs, auction-server/src/opportunity/repository/mod.rs, auction-server/src/opportunity/repository/models.rs, auction-server/src/opportunity/repository/refresh_in_memory_opportunity.rs, auction-server/src/opportunity/repository/remove_opportunities.rs, auction-server/src/opportunity/repository/remove_opportunity.rs, auction-server/src/opportunity/service/add_opportunity.rs, auction-server/src/opportunity/service/get_config.rs, auction-server/src/opportunity/service/get_opportunities.rs, auction-server/src/opportunity/service/get_quote.rs, auction-server/src/opportunity/service/mod.rs, auction-server/src/opportunity/service/remove_invalid_or_expired_opportunities.rs, auction-server/src/opportunity/service/remove_opportunities.rs, auction-server/src/opportunity/service/verification.rs
This pull requests setups a structure to test the SVM opportunity service and more broadly the auction server.
How to review this PR:
- check out `auction-server/src/opportunity/service/add_opportunity.rs` to see an example of the tests that can be written with this setup.
The opportunity service interacts with 3 external dependencies:
- the database
- the solana rpc client
- the auction service
The strategy for testing is replacing each of them with mocks whose return values we control using the crate `mockall`.  To enable mocking with mockall, I refactor the interface between the opportunity repo and the database into a trait, then I use automock to create MockOpportunityTable a mock struct that implements the trait.
Next I'd like to focus on writing tests for SVM, for both opportunity …
=> tests: write actual tests

Cargo.lock, auction-server/Cargo.toml, auction-server/src/auction/service/auction_manager.rs, auction-server/src/auction/service/conclude_auction.rs
This PR addresses the issue of halted auctions in the in-memory auction list. While this serves as a temporary workaround, we need to find a more effective long-term solution.
=> Fix svm in memory auction issue

.github/workflows/pypi-express-relay-utils.yml
GitHub deprecating Ubuntu 20.04:
https://github.com/actions/runner-images/issues/11101
=> Bump Ubuntu release

auction-server/src/auction/service/auction_manager.rs, auction-server/src/auction/service/mod.rs, auction-server/src/auction/service/optimize_bids.rs, auction-server/src/auction/service/simulator.rs, auction-server/src/auction/service/verification.rs, auction-server/src/opportunity/service/get_quote.rs
This PR enables batching the simulation of swap bids in `get_quote`, removing simulation from `handle_bid` for swap bids.
=> fix: Batch swap simulations

Cargo.lock, apps/swap/src/app/page.tsx, auction-server/Cargo.toml, auction-server/api-types/src/opportunity.rs, auction-server/api-types/src/serde.rs, auction-server/src/opportunity/api.rs, auction-server/src/opportunity/entities/quote.rs, auction-server/src/opportunity/service/get_quote.rs, sdk/js/package.json, sdk/js/src/index.ts, sdk/js/src/serverTypes.d.ts, sdk/js/src/types.ts
This PR enables ER to provide indicative prices when the `user_wallet_address` is not specified. It does this in a somewhat hacky way, reusing the `get_quote` api for ease.
TODO:
=> feat: add indicative price

auction-server/src/api.rs, auction-server/src/auction/service/cancel_bid.rs, auction-server/src/auction/service/update_bid_status.rs, auction-server/src/opportunity/service/add_opportunity.rs, auction-server/src/opportunity/service/get_quote.rs, auction-server/src/opportunity/service/mod.rs, auction-server/src/server.rs
This PR fix the issue of the `Temporary Unavailable` server response occurring in specific cases when multiple simultaneous requests are made to fetch a quote with same body at the exact same time.
=> Add temporary fix for multiple get quote requests at the same time

sdk/js/src/examples/simpleSearcherSvm.ts, sdk/js/src/serverTypes.d.ts, sdk/python/express_relay/searcher/examples/simple_searcher_svm.py, sdk/rust/simple-searcher/src/lib.rs
Changed how js simple searcher was constructing the limo bids because the submitBid instruction was coming on top.
We should probably deprecate that function later since it doesn't make a lot of sense to add the PER instruction on top of the tx.
=> feat: Add compute limit to sample searchers

auction-server/api-types/src/bid.rs, auction-server/api-types/src/ws.rs, auction-server/src/api/ws.rs, auction-server/src/server.rs, auction-server/src/state.rs
Use separate threads to process some of the time consuming requests in a single ws connection unblocking the rest. This allows higher concurrency per ws connection.
=> Feat: ws workers

Tiltfile
I ran into an api-key that started by `-` and got misinterpreted as an arg
=> fix: tilt bug

auction-server/src/api.rs, auction-server/src/auction/service/verification.rs, sdk/js/src/svm.ts, sdk/python/express_relay/client.py, sdk/rust/src/lib.rs
I want the searcher sdks to close the user WSOL atas when the user token is WSOL.
The problem: it doesn't pass verification currently.
So we also update the verification in a backward compatible way.
Longterm, we want to enforce the closing of the WSOL ata in this case.
=> feat: close user wsol ata always

auction-server/src/opportunity/service/get_quote.rs, contracts/svm/programs/express_relay/src/lib.rs, contracts/svm/programs/express_relay/src/state.rs, contracts/svm/programs/express_relay/src/swap.rs, contracts/svm/programs/express_relay/src/token.rs, contracts/svm/testing/src/express_relay/mod.rs, contracts/svm/testing/src/express_relay/set_secondary_relayer.rs, contracts/svm/testing/tests/set_secondary_relayer.rs
Changes:
- Add a secondary relayer for 0-downtime transitions between relayers
- Relax ata constraints on fee receivers: Only check their existence if the fees are positive
- Add a new instruction where swap fee bps is determined by the input
Tests to add:
- Assert second relayer works
- Test custom fees
- Test not checking atas when fees are 0
Next steps:
- Deploy program
- Accepting both instructions on the server side
- Update SDKs to use the new instruction
- Disallow the older swap instruction
- Configurable fees
=> program updates

auction-server/src/opportunity/service/get_quote_request_account_balances.rs
atas can sometimes be uninitialized but exist (when someone has airdropped some sol to the address for example)
=> fix: 0 length accounts

Tiltfile, auction-server/src/api.rs, auction-server/src/auction/repository/add_bid.rs, auction-server/src/auction/service/cancel_bid.rs, auction-server/src/auction/service/get_bid.rs, auction-server/src/auction/service/get_bids.rs, auction-server/src/auction/service/handle_auction.rs, auction-server/src/auction/service/handle_bid.rs, auction-server/src/auction/service/submit_quote.rs, auction-server/src/auction/service/update_bid_status.rs, auction-server/src/auction/service/update_recent_prioritization_fee.rs, auction-server/src/auction/service/verification.rs
This PR adds extra instrumentation decorators to important service calls to allow better tracking of failures, we currently fall back to the API style stringification of errors, as an improvement one might one to create separate tracing stringifications for Errors that have even more information.
tested manually via observing the new otel traces.
=> feat: Improve important service call instrumentation

sdk/js/src/index.ts
The BN constructor would crash if `user_mint_user_balance` is too big to warn the user `number` is not precise after a certain magnitude.
This doesn't fix the loss of precision problem, but at least it doesn't crash anymore
=> fix: don't crash for big values

auction-server/api-types/src/opportunity.rs, auction-server/src/auction/service/verification.rs, auction-server/src/opportunity/entities/opportunity_svm.rs, auction-server/src/opportunity/entities/quote.rs, auction-server/src/opportunity/repository/models.rs, auction-server/src/opportunity/service/get_quote.rs
This PR introduces a `minimum_lifetime` parameter for `get_quote` requests. It allows the Protocol to optimize pricing by requesting quotes with varying deadline windows, either shorter or longer, based on its strategy.
=> Add dynamic deadline to quote

contracts/svm/programs/express_relay/src/lib.rs, contracts/svm/programs/express_relay/src/state.rs, contracts/svm/programs/express_relay/src/swap.rs, contracts/svm/testing/src/express_relay/swap.rs, contracts/svm/testing/src/token.rs, contracts/svm/testing/tests/swap.rs
In this PR i increased the possible precision for the dynamic platform and referrer fees.
This required a bit of trickery hence the swap v2 account still used the swap v1 argument instruction data, so that the two implementations could share a context. Which has to broken here because the size of the referer fee ppm needs to be increased to u64 from u16 breaking wire compatibility. This introduces some duplication. The hack were the constraints are moved out of the account validator don't work because the instruction data still needs to deserialize properly even if we werent using fee token data.
=> feat: Add ppm precision to swap v2 fees

auction-server/src/auction/service/submit_quote.rs, auction-server/src/per_metrics.rs, auction-server/src/server.rs
This PR adds some metrics around the validation of the deadline in `submit_quote`. This will help to track the rate of swaps failing due to late submission.
=> Feat: add metrics around deadline validation

auction-server/src/opportunity/service/get_quote.rs
I noticed this while reviewing https://github.com/pyth-network/per/pull/480
=> fix: wrong fee

auction-server/api-types/src/opportunity.rs, auction-server/src/api.rs, auction-server/src/auction/service/mod.rs, auction-server/src/auction/service/submit_quote.rs, auction-server/src/auction/service/verification.rs, auction-server/src/opportunity/entities/opportunity.rs, auction-server/src/opportunity/entities/quote.rs, auction-server/src/opportunity/repository/models.rs, auction-server/src/opportunity/service/get_express_relay_metadata.rs, auction-server/src/opportunity/service/get_quote.rs, auction-server/src/opportunity/service/get_quote_request_account_balances.rs, auction-server/src/opportunity/service/mod.rs, auction-server/src/opportunity/service/unwrap_referral_fee_info.rs, contracts/svm/programs/express_relay/src/sdk/helpers.rs, contracts/svm/programs/express_relay/src/swap.rs, sdk/rust/src/svm.rs
This PR aims to add referral fee ppm to auction server quote apis
=> Add referral fee ppm to auction server

sdk/js/src/index.ts, sdk/js/src/serverTypes.d.ts, sdk/js/src/types.ts, sdk/python/express_relay/models/svm.py
This PR allows the SDK to process the profile id field added to the swap opportunity.
=> feat: add profile id processing to SDKs

auction-server/.sqlx/query-12869f012538d108ee2a3e9c98ad91daf52246ba0ebad020330288d05ac5b3c9.json, auction-server/.sqlx/query-8a16817295ec17dda1e25c36141b51f4ac67966f57636e9df36222263552c10f.json, auction-server/.sqlx/query-9526c7c80829a0dbeea7763b3381467782c8bec86f6f8b52fe11325b96edbdb4.json, auction-server/.sqlx/query-a25adc19c687c4988ca108b2ef7dedeafe298047458c91bf3bf0540274c4c508.json, auction-server/.sqlx/query-b54b6d2c1d4d7957fb7188eec17ec8a0b4e7ab51c728bac77f79ffbd896d8c27.json, auction-server/.sqlx/query-d8d976f022e66635ab32c56b9fda9ac97b4e7ef55ec3dc11bde044fc248998be.json, auction-server/.sqlx/query-e57e8bee9fbc6c2c16396d0900f44a734f7cfc94637ff3a8f1b52a329a704522.json, auction-server/.sqlx/query-f934e0aa512da01aef0c1ca76bbd48eb8a5a4983af42287088887ac3e7d6e496.json, auction-server/.sqlx/query-fa6d4023356c380d05db09464366e432a314051f152854620bd2dfcbd66434e2.json, auction-server/migrations/20250508113043_fix_expired_bid_status.down.sql, auction-server/migrations/20250508113043_fix_expired_bid_status.up.sql, auction-server/src/auction/repository/models.rs, auction-server/src/opportunity/api.rs, auction-server/src/opportunity/service/get_quote.rs
This PR aims to fix issues regarding the expired bids without auction id. The migration should take around 10 seconds on Production DB. the total number of affecting rows are less than 3K.
=> Fix issue regarding expired bids without auction id

.cargo/config.toml, Cargo.lock, auction-server/Cargo.toml, auction-server/src/per_metrics.rs, auction-server/src/server.rs
Adds tokio runtime metrics, its a bit ugly but useful
=> feat: Add tokio runtime metrics

auction-server/src/api.rs, auction-server/src/api/ws.rs, auction-server/src/per_metrics.rs, auction-server/src/server.rs
This PR aims to add profile name to ws and axum requests
=> Add profile to ws and axum http reqs

Cargo.lock, auction-server/Cargo.toml, auction-server/src/kernel/pyth_lazer.rs, auction-server/src/kernel/workers.rs, auction-server/src/opportunity/service/get_token_mint.rs
This PR aims to fix unpacking of token 2022 data
=> Fix token 2022 unpack mint data

auction-server/src/auction/repository/models.rs, auction-server/src/auction/repository/update_bid_status.rs, auction-server/src/auction/service/update_bid_status.rs
This PR updates the conclusion time in memory in order to correctly set it in the analytics db.
=> fix: add conclusion time update for analytics

Cargo.lock, auction-server/Cargo.toml, auction-server/src/kernel/analytics_db.rs
This PR increases the throughput to Clickhouse to accommodate the observed backpressure.
=> fix: increase Clickhouse db throughput

Cargo.lock, auction-server/Cargo.toml, auction-server/config.sample.yaml, auction-server/src/config.rs, auction-server/src/opportunity/service/get_quote.rs, auction-server/src/opportunity/service/mod.rs, auction-server/src/per_metrics.rs, integration.py
This PR adds a minimum fee list to the config to enable minimum fee rates for different tokens.
=> feat: minimum fee list

Cargo.lock, auction-server/Cargo.toml, auction-server/api-types/Cargo.toml, auction-server/api-types/src/opportunity.rs, auction-server/config.sample.yaml, auction-server/src/api.rs, auction-server/src/config.rs, auction-server/src/opportunity/service/get_quote.rs, auction-server/src/opportunity/service/mod.rs, integration.py, sdk/rust/Cargo.toml, sdk/rust/src/lib.rs, sdk/rust/src/svm.rs, tilt-scripts/svm/test_swap.py
This PR adds a minimum platform fees list to the config and parses it to apply platform fees based on token mints.
In order to release this feature, we need to
Longer term, we ought to
=> feat: add minimum platform fees

Cargo.lock, auction-server/Cargo.toml, auction-server/src/auction/repository/add_auction.rs, auction-server/src/auction/repository/conclude_auction.rs, auction-server/src/auction/repository/get_in_memory_auction_by_bid_id.rs, auction-server/src/auction/repository/get_in_memory_auction_by_id.rs, auction-server/src/auction/repository/get_in_memory_auctions.rs, auction-server/src/auction/repository/mod.rs, auction-server/src/auction/repository/remove_in_memory_auction.rs, auction-server/src/auction/repository/update_bid_status.rs, auction-server/src/auction/repository/update_in_memory_auction.rs, auction-server/src/auction/service/cancel_bid.rs, auction-server/src/auction/service/conclude_auction.rs, auction-server/src/auction/service/get_auction_by_id.rs, auction-server/src/auction/service/submit_quote.rs, auction-server/src/auction/service/workers.rs
This PR converts the auctions field in the `InMemoryStore` from a hash map to a dash map. Due to DashMap's integrated sharded locking, there should be less latency due to locking on queries and writes.
=> fix: convert auctions in `InMemoryStore` to `DashMap`

auction-server/migrations/20250726182247_auction_creation_time_idx.up.sql, auction-server/migrations/20250730221458_idx_bid_auction_id.down.sql, auction-server/migrations/20250730221458_idx_bid_auction_id.up.sql
This PR removes the `concurrently` from the migration query to add an index on `creation_time` to the postgres `auction` table. This is so that the migrations in `_sqlx_migrations` can remain consistent between local and the prod db. 
On local, we run this migration via the normal path since we aren't worried about downtime. However, on the prod db we had to run the migration manually in psql due to the risk of significant downtime from running this query (moreover, sqlx doesn't easily support running queries `concurrently`). 
In the prod version, we manually appended an entry to the `_sqlx_migrations` table with the checksum corresponding to the query file to indicate that the migration has taken place.
This PR also adds an index on the `auction_id` in the `bid` table; without this, the …
=> fix: add non-concurrent index creation migrations

Cargo.lock, auction-server/Cargo.toml, auction-server/src/config.rs, auction-server/src/kernel/workers.rs, integration.py
This PR drops the `delete_buffer_auction_secs` param in the `DeletePgRowsOptions`, since `auction_id` no longer has the foreign key on delete constraint so we do not have to be as careful around deleting auctions. We can use the same parameters as for bid deletions.
=> Fix: drop delete buffer auction secs
